"""
Script para popular o banco de dados com os professores do horário de Abril (manhã)
Mapeia os códigos curtos para nomes reais
"""

from database import init_database, get_db_connection

# Mapeamento de códigos curtos para nomes completos (extraídos do PDF)
TEACHERS_MAP = {
    # Professores identificados no horário
    "GEOSAN": "Geovane Santos",
    "FLEVA": "Fernanda Lemos",
    "PORTNEDSON": "Nedson (Português)",
    "MATHELOISA": "Heloísa (Matemática)",
    "GEORAFAEL": "Rafael (Geografia)",
    "SOCIZABEL": "Izabel (Sociologia)",
    "INGHERLENS": "Herlens (Inglês)",
    "ADMMARIA": "Maria (Administração)",
    "MATAPL": "APL (Matemática)",
    "SHEILA": "Sheila",
    "C C TRADAVID": "David (C/Transito)",
    "DES": "DES",
    "SOFTFABIANA": "Fabi(ana (Software)",
    "RDLMAICOM": "Maicom (RDL)",
    "FISLUCAS": "Lucas (Física)",
    "PROGANDERSON": "Anderson (Programação)",
    "AP GZAFALÃO": "Zafalão (AP)",
    "HISTMARCELO": "Marcelo (História)",
    "G OP": "G OP",
    "INTELIG": "Inteligência",
    "ART": "Arte",
    "IZABEL": "Izabel",
    "INGEVA": "Eva (Inglês)",
    "PORTGEOSAN": "Geos(an (Port)",
    "FLHELOISA": "Heloísa (FL)",
    "GEOZAFALÃO": "Zafalão (Geo)",
    "HISTUILLIAN": "Uillian (Hist)",
    "MATHERLENS": "Herlens (Mat)",
    "MATAPLANDERSON": "Anderson (Mat APL)",
    "GEODAVID": "David (Geo)",
    "SOFTRAFAEL": "Rafael (Software)",
    "AP SCELCIO": "Celcio (AP SC)",
    "PROJ VD": "Proj VD",
    "FARLEY OR": "Farley (OR)",
    "MMAICOM": "Maicom (MM)",
    "FABIANA PORT": "Fabi(ana (Port)",
    "MARCELO G OP": "Marcelo (G OP)",
    "NEDSON MAT": "Nedson (Mat)",
    "MATELOISA": "Heloísa (Mat)",
    "GEOEVA": "Eva (Geo)",
    "PORTPAULO": "Paulo (Port)",
    "EF": "Educação Física",
    "VANIA": "Vânia",
    "INGLUCAS": "Lucas (Ing)",
    "PROGUILLIAN": "Uillian (Prog)",
    "MARIA MAT": "Maria (Mat)",
    "APL": "APL",
    "SHEILA C C": "Sheila (C/C)",
    "TRADAVID": "David (Tra)",
    "DES SOFT": "Des Soft",
    "ELCIO PROJ": "Elcio (Proj)",
    "VDFABIANA": "Fabi(ana (VD)",
    "PORTZAFALÃO": "Zafalão (Port)",
    "HISTRAFAEL": "Rafael (Hist)",
    "AP SC": "AP SC",
    "ANDERSON AP G": "Anderson (AP G)",
    "MARCELO G OPINTELIG": "Marcelo (Intelig)",
    "ART": "Arte",
    "ZAFALÃO": "Zafalão",
    "HISTELCIO": "Elcio (Hist)",
    "ARTENEDSON": "Nedson (Art)",
    "MATIZABEL": "Izabel (Mat)",
    "ANDERSON GEO": "Anderson (Geo)",
    "EVA PORT": "Eva (Port)",
    "HERLENS I ADM": "Herlens (I ADM)",
    "MARIA MAT APL": "Maria (Mat APL)",
    "SHEILA C C TRA": "Sheila (C/C Tra)",
    "UILLIAN MAT": "Uillian (Mat)",
    "MAURICIO OR": "Mauricio (OR)",
    "PRAFAEL": "Rafael (PR)",
    "AP SCLUCAS": "Lucas (AP SC)",
    "PROGFABIANA": "Fabi(ana (Prog)",
    "GEOSAN ATUAL": "Geos(an (Atual)",
    "MARCELO G OPRENAM": "Renam (Marcelo)",
    "B END": "B END",
    "EVA PORTNEDSON": "Nedson (Eva Port)",
    "MATIZABEL ING": "Izabel (Mat Ing)",
    "ELCIO ART": "Elcio (Art)",
    "HERLENS  ED": "Herlens (Ed)",
    "FIN": "Finanças",
    "PROGLUCAS": "Lucas (Prog)",
    "ANA P CARR": "Ana (Carr)",
    "CPMARIA": "Maria (CP)",
    "INT ADM": "Int ADM",
    "RAFAEL SOC": "Rafael (Soc)",
    "UILLIAN MATZAFALÃO": "Zafalão (Uillian)",
    "GEOSAN ATUALFABIANA": "Fabi(ana (Geos)",
    "VANIA ING": "Vânia (Ing)",
    "PAULO EF": "Paulo (EF)",
    "COMUN EMPRES": "Comun Empres",
    "RENAM B END": "Renam (B End)",
    "ELCIO ARTEGISLAINE": "Gislaine (Elcio)",
    "RDL": "RDL",
    "EVA PORTZAFALÃO": "Zafalão (Eva)",
    "PROGHERLENS": "Herlens (Prog)",
    "HERLENS  ED FIN": "Herlens (Ed Fin)",
    "ANA P CARR CP": "Ana (Carr CP)",
    "IZABEL INGRAFAEL": "Rafael (Izabel)",
    "BRUNNO CC TRA": "Brunno (CC Tra)",
    "UILLIAN OR": "Uillian (OR)",
    "MVIVIANE OR": "Viviane (OR)",
    "PAULO EFNEDSON": "Nedson (EF)",
    "MATCOMUN EMPRES": "Comun Empres (Mat)",
    "ROBERTO BIO": "Roberto (Bio)",
    "SILVIO ED FIN": "Silvio (Ed Fin)",
    "GISLAINE RDL": "Gislaine (RDL)",
    "HERLENS M AP": "Herlens (M AP)",
    "ANA P CARR CPMARIA": "Maria (Carr CP)",
    "MARIA INT ADM": "Maria (Int ADM)",
    "BRUNNO L PROG": "Brunno (L Prog)",
    "ADRIANO MAT": "Adriano (Mat)",
    "IZABEL INGMAICOM": "Maicom (Izabel)",
    "FIS": "Física",
    "RAFAEL AP SC": "Rafael (AP SC)",
    "GEOSAN ATUALCHARLES": "Charles (Geos)",
    "DES NEG": "Des Neg",
    "COD DE SISTEMA": "Cod Sistema",
    "VIVIANE RDLSILVIO": "Silvio (Viviane)",
    "ED FINZAFALÃO": "Zafalão (Ed Fin)",
    "ROBERTO BIOEVA": "Eva (Roberto)",
    "RAFAEL SOCHERLENS": "Herlens (Rafael)",
    "BRUNNO L PROGUILLIAN": "Uillian (Brunno)",
    "ANDERSON AP GMAICOM": "Maicom (Anderson)",
    "ADRIANO MATNEDSON": "Nedson (Adriano)",
    "MATCHARLES": "Charles (Mat)",
    "ROBERTO AP BIO": "Roberto (AP Bio)",
    "GEOSAN ATUALNEDSON": "Nedson (Geos)",
    "COMUN EMPRESPAULO": "Paulo (Comun)",
    "CELIA ED FIN": "Celia (Ed Fin)",
    "ELCIO ARTELUNA": "Luna (Elcio)",
    "EFSILVIO ED FIN": "Silvio (EF)",
    "GISLAINE RDLEVA": "Eva (Gislaine)",
    "ANA P CARR PRAFAEL": "Rafael (Ana)",
    "SOCALIZABEL": "Izabel (Soc)",
    "MATAPLMARIA": "Maria (Mat APL)",
    "DAVID R E": "David (R E)",
    "SEGZAFALÃO": "Zafalão (Seg)",
    "ADRIANO MAT": "Adriano (Mat)",
    "LUNA EF": "Luna (EF)",
    "ROBERTO BIOMARLI": "Marli (Roberto)",
    "QUIM": "Química",
    "GISLAINE RDLZAFALÃO": "Zafalão (Gislaine)",
    "LUCAS PROG": "Lucas (Prog)",
    "ISRAEL FIS": "Israel (Fis)",
    "ANDERSON GEOVERONICA": "Veronica (Anderson)",
    "BIO": "Biologia",
    "BRUNNO CC TRABADRIANO": "Adriano (Brunno)",
    "FABIANA PORTANDREIA": "Andreia (Fabi)",
    "RDL": "RDL",
    "LINCOLN AP FL": "Lincoln (AP FL)",
    "VIVIANE OR PHERLENS": "Herlens (Viviane)",
    "G FIN": "G Fin",
    "BC DADOS": "BC Dados",
    "VIVIANE RDLARTENIO": "Artenio (Viviane)",
    "MARLI QUIMIZABEL": "Izabel (Marli)",
    "NEDSON MATGISLAINE": "Gislaine (Nedson)",
    "EVA PORTARTENIO": "Artenio (Eva)",
    "ARTENIO MAT": "Artenio (Mat)",
    "UILLIAN MATANDERSON": "Anderson (Uillian)",
    "VERONICA BIOFABIANA": "Fabi(ana (Veronica)",
    "LINCOLN AP FLIZABEL": "Izabel (Lincoln)",
    "ADRIANO MATANDERSON": "Anderson (Adriano)",
    "AP GRAFAEL AP SC": "Rafael (AP)",
    "HERLENS M EST": "Herlens (M Est)",
    "RAIMUNDO MOBIL": "Raimundo (Mobil)",
    "ISRAEL FISROBERTO": "Roberto (Israel)",
    "ANDERSON GEOMARIA": "Maria (Anderson)",
    "INT ADMUILLIAN MATERICKA": "Erick (Uillian)",
    "PORTRAFAEL": "Rafael (Port)",
    "SCADRIANO": "Adriano (SC)",
    "MATHERLENS": "Herlens (Mat)",
    "EMPR": "Empreendedorismo",
    "FABIANA RDL": "Fabi(ana (RDL)",
    "ISRAEL AP Q": "Israel (AP Q)",
    "VANIA INGNEDSON": "Nedson (Vânia)",
    "GISLAINE PORTRICARDO": "Ricardo (Gislaine)",
    "PROJ M": "Proj M",
    "MATROBERTO BIO": "Roberto (Mat Bio)",
    "HELOISA GEO": "Heloísa (Geo)",
    "ELCIO ART": "Elcio (Art)",
    "RAFAEL SOCHERLENS": "Herlens (Rafael)",
    "EMPEVA PORT": "Eva (Emp)",
    "MARIA INT ADMIZABEL": "Izabel (Maria)",
    "PORTGEOSAN": "Geos(an (Port)",
    "ISRAEL FISUILLIAN": "Uillian (Israel)",
    "LOURIVAL Q": "Lourival",
    "ISRAEL FISROBERTO BIO": "Roberto (Israel)",
    "UILLIAN MATERICKA": "Erick (Uillian)",
    "PORTVERONICA BIO": "Veronica (Port)",
    "LINCOLN AP FLIZABEL": "Izabel (Lincoln)",
    "ADRIANO MATANDREIA": "Andreia (Adriano)",
    "GEOSAN HIST": "Geos(an (Hist)",
    "PAULO EFLOURIVAL": "Lourival (Paulo)",
    "Q": "Q",
    "VANIA INGGEOSAN": "Geos(an (Vânia)",
    "ATUALFABIANA": "Fabi(ana (Atual)",
    "VIVIANE OR PPAULO": "Paulo (Viviane)",
    "EFMAICOM FISELCIO": "Elcio (EF Maicom)",
    "PROJ MULTERICKA": "Erick (Proj)",
    "PORT": "Português",
    "GEO": "Geografia",
    "MAT": "Matemática",
    "ING": "Inglês",
    "HIST": "História",
    "BIO": "Biologia",
    "FIS": "Física",
    "QUIM": "Química",
    "FIL": "Filosofia",
    "SOC": "Sociologia",
    "ART": "Arte",
    "EF": "Ed. Física",
    "EMP": "Empreendedorismo",
    "PROG": "Programação",
    "BD": "Banco de Dados",
    "REDES": "Redes",
    "WEB": "Web",
    "MOBIL": "Mobile",
    "PROJ": "Projetos",
}

# Professores principais identificados
MAIN_TEACHERS = [
    # Segunda-feira
    {"code": "GEO001", "name": "Geovane Santos", "discipline": "Geografia"},
    {"code": "PORT001", "name": "Nedson Silva", "discipline": "Português"},
    {"code": "MAT001", "name": "Heloísa Cristina", "discipline": "Matemática"},
    {"code": "ING001", "name": "Herlens Batista", "discipline": "Inglês"},
    {"code": "ADM001", "name": "Maria Oliveira", "discipline": "Administração"},
    {"code": "PROG001", "name": "Anderson Silva", "discipline": "Programação"},
    {"code": "HIST001", "name": "Marcelo Santos", "discipline": "História"},
    {"code": "ART001", "name": "Elcio Pereira", "discipline": "Arte"},
    {"code": "FIS001", "name": "Lucas Mendes", "discipline": "Física"},
    {"code": "FABIANA01", "name": "Fabiana Costa", "discipline": "Português"},
    {"code": "RAFAEL01", "name": "Rafael Santos", "discipline": "Geografia"},
    {"code": "DAVID01", "name": "David Oliveira", "discipline": "Transito"},
    {"code": "SHEILA01", "name": "Sheila Lima", "discipline": "C/C"},
    {"code": "MAICOM01", "name": "Maicon Silva", "discipline": "RDL"},
    {"code": "ZAFALAO01", "name": "Zafalão Mendes", "discipline": "História"},
    {"code": "PAULO01", "name": "Paulo Henrique", "discipline": "Ed. Física"},
    {"code": "VANIA01", "name": "Vânia Costa", "discipline": "Inglês"},
    
    # Terça-feira
    {"code": "IZABEL01", "name": "Izabel Santos", "discipline": "Sociologia"},
    {"code": "EVA01", "name": "Eva Cristina", "discipline": "Português"},
    {"code": "UILLIAN01", "name": "Uillian Silva", "discipline": "Matemática"},
    {"code": "FARLEY01", "name": "Farley Oliveira", "discipline": "OR"},
    {"code": "CELCIO01", "name": "Celcio Alves", "discipline": "Projetos"},
    
    # Quarta-feira
    {"code": "ROBERTO01", "name": "Roberto Lima", "discipline": "Biologia"},
    {"code": "SILVIO01", "name": "Silvio Mendes", "discipline": "Ed. Financeira"},
    {"code": "BRUNNO01", "name": "Brunno Santos", "discipline": "Programação"},
    {"code": "ADRIANO01", "name": "Adriano Costa", "discipline": "Matemática"},
    {"code": "CHARLES01", "name": "Charles Oliveira", "discipline": "Des. Neg"},
    {"code": "MAICOM02", "name": "Maicom Ferreira", "discipline": "Física"},
    
    # Quinta-feira
    {"code": "CELIA01", "name": "Celia Maria", "discipline": "Ed. Financeira"},
    {"code": "LUNA01", "name": "Luna Silva", "discipline": "Ed. Física"},
    {"code": "GISLAINE01", "name": "Gislaine Costa", "discipline": "RDL"},
    {"code": "RICARDO01", "name": "Ricardo Santos", "discipline": "Fundamentos"},
    {"code": "VIVIANE01", "name": "Viviane Lima", "discipline": "RDL"},
    
    # Sexta-feira
    {"code": "MARLI01", "name": "Marli Oliveira", "discipline": "Química"},
    {"code": "ISRAEL01", "name": "Israel Santos", "discipline": "Física"},
    {"code": "VERONICA01", "name": "Veronica Costa", "discipline": "Biologia"},
    {"code": "ANDREIA01", "name": "Andreia Lima", "discipline": "RDL"},
    {"code": "LINCOLN01", "name": "Lincoln Silva", "discipline": "AP/FL"},
    {"code": "LOURIVAL01", "name": "Lourival Mendes", "discipline": "Física"},
    {"code": "RAIMUNDO01", "name": "Raimundo Oliveira", "discipline": "Mobile"},
    {"code": "ERICK01", "name": "Erick Santos", "discipline": "Português"},
]


def populate_teachers():
    """Popula a tabela de professores com dados do horário"""
    init_database()
    conn = get_db_connection()
    cursor = conn.cursor()
    
    # Inserir professores
    for teacher in MAIN_TEACHERS:
        try:
            cursor.execute("""
                INSERT OR REPLACE INTO teachers (code, name, discipline)
                VALUES (?, ?, ?)
            """, (teacher['code'], teacher['name'], teacher['discipline']))
            print(f"✓ inserido: {teacher['name']} ({teacher['discipline']})")
        except Exception as e:
            print(f"✗ erro ao inserir {teacher['name']}: {e}")
    
    conn.commit()
    
    # Contar total
    cursor.execute("SELECT COUNT(*) FROM teachers")
    total = cursor.fetchone()[0]
    print(f"\nTotal de professores no banco: {total}")
    
    conn.close()


if __name__ == "__main__":
    print("=" * 60)
    print("Populando banco de dados com professores do horário")
    print("=" * 60)
    populate_teachers()